services:
  techmove_logistics:
    image: techmovelogistics:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TechMove_Logistics"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_techmove_logistics$
    volumes:
      - C:\Users\saman\Desktop\part-2-the-core-prototype-unit-testing-samanthadeysel\Tech_moves_part2\TechMove_Logistics\TechMove_Logistics:c:\app:rw
      - C:\Users\saman\Desktop\part-2-the-core-prototype-unit-testing-samanthadeysel\Tech_moves_part2\TechMove_Logistics:c:\src:rw
      - C:\Users\saman\onecoremsvsmon\18.5.10309.8850:c:\remote_debugger:ro
#$nuget_volume_mapping_techmove_logistics$
      - C:\Users\saman\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
      - C:\Users\saman\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerAdministrator\AppData\Roaming\ASP.NET\Https:ro
      - C:\Users\saman\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - C:\Users\saman\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerAdministrator\AppData\Roaming\Microsoft\UserSecrets:ro
      - C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\win-x64\net6.0:C:\VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\extensions\Microsoft\managedprojectsystem\HotReload:C:\HotReloadAgent:ro

    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646 /LogDebuggeeOutputToStdOut
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_techmove_logistics$ \"C:\\app\\bin\\Debug\\net10.0\\TechMove_Logistics.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major C:\\VSTools\\DistrolessHelper\\DistrolessHelper.dll --stop dotnet"
